# Generated by Django 3.2 on 2021-05-01 00:15

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0004_auto_20210430_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('dt_criacao', models.DateTimeField(auto_now=True)),
                ('endereco', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=13)),
                ('telefone', models.CharField(max_length=11)),
                ('curriculo', models.ImageField(blank=True, null=True, upload_to='pdf')),
                ('dt_criacao', models.DateTimeField(auto_now=True)),
                ('endereco', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dt_abertura', models.DateTimeField()),
                ('dt_fechamento', models.DateTimeField()),
                ('texto', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='ativa', max_length=100)),
                ('dt_criacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='painel.empresa')),
                ('endereco', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_aplicacao', models.DateTimeField()),
                ('status', models.CharField(choices=[('Andamento', 'andamento'), ('Aprovado', 'aprovado'), ('Reprovado', 'reprovado'), ('Congelado', 'congelado')], default='Andamento', max_length=100)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='painel.participante')),
                ('vaga', models.ManyToManyField(to='painel.Vaga')),
            ],
        ),
    ]
