# Generated by Django 3.2 on 2021-05-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('Presencial', 'presencial'), ('Remoto', 'remoto'), ('Híbrido', 'híbrido')], default='Presencial', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('Ativa', 'ativa'), ('Inativa', 'inativa')], default='ativa', max_length=100),
        ),
    ]
