# Generated by Django 3.2 on 2021-05-11 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_auto_20210430_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_vagas', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='painel.empresa')),
                ('vaga', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='painel.vaga')),
            ],
        ),
    ]
